### PR TITLE
Fix loading behaviour by passing null callback

### PR DESCRIPTION
**Pull request by j1mie**
Corrects constant loading issue with react-select using fix described here: https://github.com/JedWatson/react-select/issues/895

resolves https://github.com/conveyal/react-select-geocoder/issues/41

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
Thanks for the PR @j1mie! Test is failing on Travis CI but not entirely sure why since it looks like you updated the snapshots appropriately. We'll need to resolve that before we can merge that in 🤔

**Comment by trevorgerhardt** [comment]
@j1mie it appears that a mismatch between [react-select](https://github.com/JedWatson/react-select) versions is causing the snapshots to differ. Can you pin react-select directly to version rc.10 in the dependencies and push again? Make sure to remove the `^` symbol so it's hard pinned to a specific version. Thanks!

```js
"dependencies": {
    "isomorphic-mapzen-search": "^1.3.0",
    "json-stable-stringify": "^1.0.1",
    "lodash": "^4.17.4",
    "prop-types": "^15.5.10",
    "react-select": "1.0.0-rc.10"
  }
```

**Comment by j1mie** [comment]
@trevorgerhardt Odd - tests ran fine locally. I will indeed. Thanks!

**Comment by evansiroky** [comment]
Hey, we haven't heard back from you, but like the work you've done and want to start using your changes right away!  We're going to go ahead and merge this into a branch where we'll make the final changes needed.

**Comment by j1mie** [comment]
Sorry for the delay, thanks for merging in! 👍

**Pull request merged**
